export const countries = [
  ['Australia', "au"],
  ['Brazil', "br"],
  ['Canada', "ca"],
  ['China',"cn"],
  ['Egypt', "eg"],
  ['France', "fr"],
  ['Germany', "de"],
  ['Greece',"gr"],
  ["Hong Kong", "hk"],
  ['India', "in"],
  ['Ireland', "ie"],
  ['Israel',"il"],
  ['Italy',"it"],
  ['Japan', "jp"],
  ['Netherlands', "nl"],
  ['Norway', "no"],
  ['Pakistan', "pk"],
  ["Peru", "pe"],
  ["Philippines", "ph"],
  ["Portugal", "pt"],
  ["Romania","ro"],
  ["Russian Federation", "ru"],
  ["Singapore", "sg"],
  ["Spain", "es"],
  ["Sweden", "se"],
  ["Switzerland", "ch"],
  ["Taiwan", "tw"],
  ["Ukraine", "ua"],
  ["United Kingdom", "gb"],
  ["United States", "us"],
];
